/*!
 * @file hospital_manager.c
 *
 * @brief Hospital manager source file
 * @details This file contains the implementation of the functions for the hospital manager module.
 *
 * @author CrimsonCare Team
 * @date 2025-01-18
 *
 * @copyright
 * Copyright (c) 2025 CrimsonCare Team
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include "../include/hospital_manager.h"

 /*!
  * @brief Hospital head pointer
  * @details This pointer is used to track hospital linkedlist on runtime.
  */
Hospital* hospitalHead = NULL;

/*!
 * @name loadHospitals
 * @brief Load hospitals from file
 * @details This function loads the hospitals from the file `resources/db/hospitals.txt`
 * and stores it in the `hospitalHead` linkedlist.
 *
 * @note The file path 'resources/db' is relative to the project root directory.
 * Make sure that the folder exists also to run the program from the root directory.
 *
 * @post If the file is not found, the function does nothing. Otherwise, the hospitals
 * are loaded from the file and stored in the `hospitalHead` linkedlist.
 *
 * @exception fopen() - If the file cannot be opened, an error message is displayed,
 * also the function frees the `hospitalHead` linkedlist.
 * @exception malloc() - If memory allocation fails, an error message is displayed,
 * also the function frees the `hospitalHead` linkedlist.
 */
void loadHospitals(void) {
    errno = 0;
    FILE* file = fopen("resources/db/hospitals.txt", "r");
    if (!file) {
        if (errno == ENOENT) {
            return;
        } else {
            printf("Error opening hospitals file: %s\n", strerror(errno));
            freeHospital();
            return;
        }
    }

    while (1) {
        Hospital* newHospital = (Hospital*)malloc(sizeof(Hospital));
        if (!newHospital) {
            printf("Error allocating memory for hospital: %s\n", strerror(errno));
            fclose(file);
            freeHospital();
            return;
        }

        if (fscanf(file, "%[^|]|%[^|]|%[^\n]\n", newHospital->code, newHospital->name, newHospital->location) != 3) {
            free(newHospital);
            fclose(file);
            break;
        }

        newHospital->next = NULL;

        if (hospitalHead == NULL) {
            hospitalHead = newHospital;
        } else {
            Hospital* temp = hospitalHead;
            while (temp->next != NULL) {
                temp = temp->next;
            }
            temp->next = newHospital;
        }
    }

    fclose(file);
}

/*!
 * @name saveHospitals
 * @brief Save hospitals to file
 * @details This function saves the hospitals to the file `resources/db/hospitals.txt`.
 *
 * @note The file path 'resources/db' is relative to the project root directory.
 * Make sure that the folder exists also to run the program from the root directory.
 *
 * @post The hospitals from the `hospitalHead` linkedlist are saved to the file.
 *
 * @exception fopen() - If the file cannot be opened, an error message is displayed.
 */
void saveHospitals(void) {
    errno = 0;
    FILE* file = fopen("resources/db/hospitals.txt", "w");
    if (!file) {
        printf("Error opening hospitals file: %s\n", strerror(errno));
        return;
    }

    Hospital* temp = hospitalHead;
    while (temp != NULL) {
        fprintf(file, "%s|%s|%s\n", temp->code, temp->name, temp->location);
        temp = temp->next;
    }
    fclose(file);
}

/*!
 * @name addHospital
 * @brief Add hospital
 * @details This function adds a new hospital to the `hospitalHead` linkedlist.
 *
 * @param[in] name Hospital name
 * @param[in] location Hospital location
 *
 * @return Hospital code or NULL if hospital is not added
 *
 * @note The hospital code is generated by taking the maximum of the first three
 * characters of the hospital name and appending a random number between 0000 and 9999.
 *
 * @pre @p name is not empty and valid
 * @pre @p location is not empty and valid
 * @post The hospital is added to the `hospitalHead` linkedlist.
 *
 * @exception If the @p name or @p location is empty or invalid, an error message is displayed.
 * @exception malloc() - If the memory allocation for the new hospital fails, an error message is displayed.
 */
char* addHospital(const char* name, const char* location) {
    if (strcmp(name, "") == 0 || strcmp(location, "") == 0) {
        printf("Error: Hospital name or location cannot be empty.\n");
        return NULL;
    }

    if (containsPipe(name) || containsPipe(location)) {
        printf("Error: Hospital name or location cannot contain a pipe character.\n");
        return NULL;
    }

    char code[8];
    char initials[4] = { 0 };
    int initialCount = 0;

    char nameCopy[100];
    strncpy(nameCopy, name, sizeof(nameCopy) - 1);
    nameCopy[sizeof(nameCopy) - 1] = '\0';

    char* token = strtok(nameCopy, " ");
    while (token != NULL && initialCount < 3) {
        initials[initialCount++] = token[0];
        token = strtok(NULL, " ");
    }
    initials[initialCount] = '\0';

    bool codeExists;
    int randomSuffix;
    do {
        srand(time(NULL));
        randomSuffix = rand() % 10000;
        snprintf(code, sizeof(code), "%s%04d", initials, randomSuffix);

        codeExists = false;
        Hospital* temp = hospitalHead;
        while (temp != NULL) {
            if (strcmp(temp->code, code) == 0) {
                codeExists = true;
                break;
            }
            temp = temp->next;
        }
    } while (codeExists);

    Hospital* newHospital = (Hospital*)malloc(sizeof(Hospital));
    if (!newHospital) {
        printf("Error allocating memory for hospital: %s\n", strerror(errno));
        return NULL;
    }

    strncpy(newHospital->code, code, sizeof(newHospital->code) - 1);
    newHospital->code[sizeof(newHospital->code) - 1] = '\0';
    strncpy(newHospital->name, name, sizeof(newHospital->name) - 1);
    newHospital->name[sizeof(newHospital->name) - 1] = '\0';
    strncpy(newHospital->location, location, sizeof(newHospital->location) - 1);
    newHospital->location[sizeof(newHospital->location) - 1] = '\0';
    newHospital->next = NULL;

    if (hospitalHead == NULL) {
        hospitalHead = newHospital;
    } else {
        Hospital* temp = hospitalHead;
        while (temp->next != NULL) {
            temp = temp->next;
        }
        temp->next = newHospital;
    }

    saveHospitals();
    return newHospital->code;
}

/*!
 * @name validateHospitalCode
 * @brief Validate hospital code
 * @details This function validates the given hospital code by
 * traversing the `hospitalHead` linkedlist.
 *
 * @param[in] code Hospital code
 *
 * @return True if hospital code is valid, False otherwise
 *
 * @pre @p code is not empty and valid
 * @post If the @p code is found in the `hospitalHead` linkedlist,
 * the function returns true. Otherwise, it returns false.
 *
 * @exception If the @p code is empty or invalid, an error message is displayed.
 */
bool validateHospitalCode(const char* code) {
    if (strcmp(code, "") == 0) {
        printf("Error: Hospital code cannot be empty.\n");
        return false;
    }

    if (containsPipe(code)) {
        printf("Error: Hospital code cannot contain a pipe character.\n");
        return false;
    }

    Hospital* temp = hospitalHead;
    while (temp != NULL) {
        if (strcmp(temp->code, code) == 0) {
            return true;
        }
        temp = temp->next;
    }
    return false;
}

/*!
 * @name deleteHospital
 * @brief Delete hospital
 * @details This function deletes the hospital with the given code
 * by traversing the `hospitalHead` linkedlist.
 *
 * @param[in] code Hospital code
 * @param[in] adminUsername Admin username
 * @param[in] adminPassword Admin password
 *
 * @return True if hospital is deleted, False otherwise
 *
 * @pre @p code is not empty and valid
 * @pre @p adminUsername is not empty and valid
 * @pre @p adminPassword is not empty
 * @post The hospital with the given code is deleted from the `hospitalHead` linkedlist.
 *
 * @exception If the @p code is empty or invalid, an error message is displayed.
 * @exception If the @p adminUsername is empty or invalid or @p adminPassword is empty, an error message is displayed.
 * @exception If the pair of @p adminUsername and @p adminPassword is invalid, an error message is displayed.
 * @exception If the hospital with the given code is not found, an error message is displayed.
 */
bool deleteHospital(const char* code, const char* adminUsername, const char* adminPassword) {
    if (strcmp(adminUsername, "") == 0 || strcmp(adminPassword, "") == 0) {
        printf("Error: Admin credentials cannot be empty.\n");
        return false;
    }

    if (!checkUsername(adminUsername)) {
        printf("Error: Invalid admin username. Username can only contain lowercase letters and digits.\n");
        return false;
    }

    if (!validateAdmin(adminUsername, adminPassword)) {
        printf("Error: Invalid admin credentials.\n");
        return false;
    }

    if (strcmp(code, "") == 0) {
        printf("Error: Hospital code cannot be empty.\n");
        return false;
    }

    if (containsPipe(code)) {
        printf("Error: Hospital code cannot contain a pipe character.\n");
        return false;
    }

    if (!validateHospitalCode(code)) {
        printf("Error: Hospital code is invalid.\n");
        return false;
    }

    Hospital* current = hospitalHead;
    Hospital* prev = NULL;
    while (current != NULL) {
        if (strcmp(current->code, code) == 0) {
            if (prev == NULL) {
                hospitalHead = current->next;
            } else {
                prev->next = current->next;
            }
            saveHospitals();
            return true;
        }
        prev = current;
        current = current->next;
    }
    return false;
}

/*!
 * @name getHospitalNameByCode
 * @brief Get hospital name by code
 * @details This function gets the hospital name by the given code
 * by traversing the `hospitalHead` linkedlist.
 *
 * @param[in] code Hospital code
 *
 * @return Hospital name or NULL if not found
 *
 * @pre @p code is not empty and valid
 * @post If the @p code is found in the `hospitalHead` linkedlist,
 * the function returns the hospital name. Otherwise, it returns NULL.
 *
 * @exception If the @p code is empty or invalid, an error message is displayed.
 */
char* getHospitalNameByCode(const char* code) {
    if (strcmp(code, "") == 0) {
        printf("Error: Hospital code cannot be empty.\n");
        return NULL;
    }

    if (containsPipe(code)) {
        printf("Error: Hospital code cannot contain a pipe character.\n");
        return NULL;
    }

    if (!validateHospitalCode(code)) {
        printf("Error: Hospital code is invalid.\n");
        return NULL;
    }

    Hospital* temp = hospitalHead;
    while (temp != NULL) {
        if (strcmp(temp->code, code) == 0) {
            return temp->name;
        }
        temp = temp->next;
    }
    return NULL;
}

/*!
 * @name displayHospitals
 * @brief Display all hospitals
 * @details This function displays all the hospitals
 * in the `hospitalHead` linkedlist by traversing it.
 *
 * @post The hospitals in the `hospitalHead` linkedlist are displayed in a formatted manner.
 */
void displayHospitals(void) {
    Hospital* temp = hospitalHead;
    if (temp == NULL) {
        printf("No hospitals registered yet.\n");
        return;
    }
    printf("\nRegistered Hospitals:\n");
    while (temp != NULL) {
        printf("\tCode: %s\n"
            "\tName: %s\n"
            "\tLocation: %s\n", temp->code, temp->name, temp->location);
        temp = temp->next;
        if (temp != NULL) {
            printf("\t----------------------------------\n");
        }
    }
}

/*!
 * @name freeHospital
 * @brief Free hospital list from memory
 * @details This function frees the `hospitalHead` linkedlist
 * from memory by traversing it.
 *
 * @post The `hospitalHead` linkedlist is freed from memory.
 */
void freeHospital(void) {
    Hospital* current = hospitalHead;
    while (current != NULL) {
        Hospital* temp = current;
        current = current->next;
        free(temp);
    }
    hospitalHead = NULL;
}
